### PR TITLE
Use AddressResolver to Query futuresManager address

### PR DESCRIPTION
**Pull request by JaredBorders**
closes https://github.com/Kwenta/margin-manager/issues/29

### CODE REVIEW

**Comment by JChiaramonte7** [comment]
but if address resolver eventually points to perps v2 futures manager isn't that an issue? because our system won't be compatible with v2

**Comment by JaredBorders** [comment]
Looking into this further. Asked Arthur about it. Would be nice to have some sort of compatibility (i.e. allow users to exit or migrate positions to perps v2) but we'd need to know more about perps v2

**Comment by JaredBorders** [comment]
based on convo in Synthetix discord, should we just close this? @JChiaramonte7

**Comment by JChiaramonte7** [comment]
Yes, close is fine, also prob doesnt make sense to develop something for unknown future functionality

**Pull request closed without merging**
